# Use custom format
format = '''[┌───────────────────>](bold green)
[│](bold green)$directory$rust$package
[└─>](bold green) '''

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
format = " 🕙 $duration($style) "
style = "bold italic #87A752"
